[phases.setup]
nixpkgs = ["python3", "gcc", "gnumake", "openjdk", "libffi", "libffi.dev", "python3.dev"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"
